pipeline {
    agent any
    stages {
        stage('Deploy - Staging') {
            steps {
                echo 'deploying staging'
            }
        }

        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }

        stage('Deploy - Production') {
            steps {
                echo 'deploying production'
            }
        }
    }
}